name: fourth workflow demo
on:
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:
  push:
    branches: 
      - main 
      - demo_branch
      - 'dev_*'
    paths-ignore:
      -'README.md'
      -'.github/workflows/*'
jobs:
  gather_info:
    runs-on: ubuntu-latest
    steps:
    - name: output info
      run: echo "${{ toJSON (github)}}"